knative-extensions/kn-plugin-operator

OWNERS
OWNERS_ALIASES

- Create the initial owners.
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Add the OWNERS and OWNERS_ALIASES

---

pkg/command/common/file.go
pkg/command/common/file_test.go
pkg/command/common/testdata/test.txt
pkg/command/testingUtil/util.go

- This PR added some basic functions regarding files, including reading, writing and deleting a file.
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Add some basic functions regarding files

---

go.mod
pkg/command/common/namespace.go
vendor/modules.txt

- Created a struct to create the namespace if it is not available in the cluster for different Knative components.
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Add the module to handle the namespace resource

---

go.mod
go.sum
pkg/command/common/version.go
pkg/command/common/version_test.go
pkg/command/install/install.go
pkg/command/install/install_test.go
third_party/VENDOR-LICENSE/golang.org/x/mod/semver/LICENSE
vendor/golang.org/x/mod/LICENSE
vendor/golang.org/x/mod/PATENTS
vendor/golang.org/x/mod/semver/semver.go
vendor/modules.txt

- This PR added a function to generate the download url based on the input version.
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Add the module to generate the download URL

---

overlay/operator.yaml
pkg/command/common/file.go
pkg/command/common/namespace.go
pkg/command/install/install.go

- This PR implemented the installation of knative operator based on the version and the namespace.
/kind <kind>
Fixes #21
```release-note
```
**Docs**
```docs
```

Implement the installation of the operator

---

pkg/command/common/constants.go
pkg/command/install/install.go
pkg/command/install/install_test.go

- Added the default values for InstallCmdFlags.

Add the default value for InstallCmdFlags

---

pkg/command/install/install.go

This PR added the configuration option to configure the kubeconfig.

Make the kubeconfig configurable

---

pkg/command/uninstall/uninstall.go

- Uninstall Knative operator "kn operation uninstall".
- Uninstall Knative Serving "kn operation uninstall -c serving --namespace knative-serving".
- uninstall knative eventing with "kn operation uninstall -c eventing --namespace knative-eventing".
/kind <kind>
Fixes #56 
```release-note
```
**Docs**
```docs
```

Implement the uninstallation of Knative operator and components

---

overlay/ke_source.yaml
pkg/command/enable/eventingsource.go
pkg/command/enable/eventingsource_test.go
pkg/command/enable/ingress.go
pkg/command/enable/ingress_test.go

Add the support to install eventing sources

---

core/root.go
overlay/ke_resource_base.yaml
overlay/ks_resource_base.yaml
pkg/command/common/constants.go
pkg/command/common/constants_test.go
pkg/command/common/knative_operator.go
pkg/command/common/ytttag.go
pkg/command/common/ytttag_test.go
pkg/command/configure/configure.go
pkg/command/configure/resource.go
pkg/command/configure/resource_test.go
pkg/command/configure/testdata/overlay/ke_resource_base.yaml
pkg/command/configure/testdata/overlay/ks_resource_base.yaml
pkg/command/enable/eventingsource_test.go

- This PR implements the resource configuration for the container on the pod level. The support parameters include CPU and memory in limits and CPU and memory in requests.
/kind <kind>
Fixes #73
```release-note
```
**Docs**
```docs
```

Implement the resource configuration

---

overlay/ke_toleration.yaml
overlay/ks_toleration.yaml
pkg/command/common/strings.go
pkg/command/common/strings_test.go
pkg/command/configure/configure.go
pkg/command/configure/resource.go
pkg/command/configure/resource_test.go
pkg/command/configure/testdata/overlay/ke_toleration.yaml
pkg/command/configure/testdata/overlay/ks_toleration.yaml
pkg/command/configure/toleration.go
pkg/command/configure/toleration_test.go

- This PR implements the configuration of tolerations for the deployment.
/kind <kind>
Fixes #74
```release-note
```
**Docs**
```docs
```

Implement the configuration of tolerations for the deployment

---

overlay/ke_replica.yaml
overlay/ks_replica.yaml
pkg/command/configure/configure.go
pkg/command/configure/ha.go
pkg/command/configure/ha_test.go
pkg/command/configure/testdata/overlay/ke_replica.yaml
pkg/command/configure/testdata/overlay/ks_replica.yaml

- This pr makes it possible to configure the global HA for all deployments or the number of replicas for a specific deployment.
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Implement the configuration of HA replicas for Knative

---

overlay/ke_cm_base.yaml
overlay/ks_cm_base.yaml
pkg/command/configure/configmap.go
pkg/command/configure/configmap_test.go
pkg/command/configure/configure.go
pkg/command/configure/testdata/overlay/ke_cm_base.yaml
pkg/command/configure/testdata/overlay/ks_cm_base.yaml

- This PR makes it possible to configure all Knative CMs via the command line.
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Implement the configuration of ConfigMaps for Knative

---

overlay/operator.yaml
overlay/operator_crds.yaml
pkg/command/common/knative_operator.go
pkg/command/install/install.go
pkg/command/install/install_test.go
pkg/command/install/testdata/overlay/full_operator.yaml
pkg/command/install/testdata/overlay/operator.yaml
pkg/command/install/testdata/overlay/operator_crds.yaml

- This PR updated the template to install knative operator 1.3 or later.
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Fix the template issue for the Knative Operator 1.3 or later

---

pkg/command/common/knative_operator.go
vendor/k8s.io/client-go/util/retry/util.go
vendor/modules.txt

This PR resolves the error of "the object has been modified; please apply your changes to the latest version and try again".

Add the retry mechanism to apply the manifests

---

core/root.go
pkg/command/common/knative_operator.go
pkg/command/remove/remove.go
pkg/command/remove/resource.go
pkg/command/remove/resource_test.go
test/e2e-tests.sh
test/e2e/eventingresourcedelete_test.go
test/e2e/servingresourcedelete_test.go
test/resources/verify.go

- This PR implements the removal of resource configurations.
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Implement the deletion of resource configurations

---

overlay/operator.yaml
pkg/command/install/install.go
pkg/command/install/install_test.go

Fix the installation issue of operator under a specific namespace

---

overlay/ke_source.yaml
pkg/command/enable/enable.go
pkg/command/enable/eventingsource.go
pkg/command/enable/ingress.go

-
-
-
/kind <kind>
Fixes #195 
```release-note
```
**Docs**
```docs
```

Fix the eventing source issue with the command

---

pkg/command/remove/ha.go
pkg/command/remove/ha_test.go
test/e2e-tests.sh
test/resources/verify.go

Fixes #211
```release-note
```
**Docs**
```docs
```

Set the high-availability to empty instead of replicas

---

go.mod
go.sum
vendor/knative.dev/pkg/apis/duck/v1/destination.go
vendor/modules.txt

- This PR updates the deps for 1.9 release.
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Update the deps for 1.9 release
